repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
        args: [ --maxkb=1000 ]
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff-format
        types_or: [ python, ]
      - id: ruff
        types_or: [ python, ]
        args: [ --fix ]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-lock
        entry: poetry lock --check
      - id: poetry-check
